on:
  push:
    branches:
      - ci
    tags:
      - v*
  workflow_dispatch:

name: create-release

jobs:
  release:
    name: Create release

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable

      - name: Build project
        run: cargo build --release
